spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/imooc_demo?&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  session:
    store-type: none
  upload:
    path: src/main/resources/upload




server:
  port: 8090


security:
  basic:
    enabled: false







